//! The generated projections: `KANSPEC-FEATURES.md` and `KANSPEC-ARCHITECTURE.md`, both
//! written to the **repo root** where a teammate browsing GitHub will find them.
//!
//! Projections cannot rot independently of their sources — which is exactly why they are
//! safe to put in plain sight. Regenerated on `scan`, and by **every verb that changes a
//! spec, a decision or a quirk** (D-20), through `Op::WriteGenerated` in a short
//! transaction of its own immediately after the write (D-34, see [`regenerate`]).
//!
//! # A committed file is a pure function of the committed corpus
//!
//! These two files are **git-tracked**, which fixes what may appear in them: every byte
//! must be derivable from the git-tracked sources of the same commit, and from nothing
//! else. Two clones of one commit must regenerate identical bytes, or the projection stops
//! being a projection and becomes a per-machine artifact that conflicts on merge and lies
//! in a PR diff.
//!
//! Two things are therefore excluded, for the same reason:
//!
//! * **The clock.** DESIGN.md's mock-up carries a "regenerated <date>" line; it is
//!   deliberately absent. A timestamp would make every `scan` — which the `post-merge` and
//!   `post-checkout` hooks run on every checkout — produce a one-line git diff, and a
//!   projection that dirties the tree on every checkout is one a human deletes from their
//!   repo within a week.
//! * **`cache/gitstate.json`.** DESIGN.md's mock-up also carries a `Fresh?` column, and it
//!   is absent for a sharper reason: [`Staleness`] is computed from the *disposable* cache,
//!   so the same commit renders `never scanned` on a fresh clone and `ok` — or
//!   `dead globs: …` — once someone has run `scan`. Freshness is live board furniture, not
//!   a committed fact; it stays on the `features` table, the `spec show` footer and the
//!   board's feature strip, all of which are read at the moment they are printed.
//!
//! What is left is `feature:` + `code:` + the `{p-xxxx}` provenance tokens, all of which
//! live in the spec files themselves. Rendered purely from those, an unchanged corpus
//! rewrites byte-identical bytes and `git status` stays silent.
//!
//! Owner: **S6**.

use serde::Serialize;

use crate::derive::{self, Staleness};
use crate::error::Result;
use crate::ids::SpecName;
use crate::model::{DecisionStatus, QuirkStatus, Severity, Snapshot};
use crate::paths::Layout;
use crate::plan::Op;

/// The header that stops hand-edits. Present on both projections, byte-identical.
pub const GENERATED_HEADER: &str =
    "<!-- GENERATED by kanspec. Edit the sources (.kanspec/specs, .kanspec/decisions), not this file. -->";

#[derive(Debug, Clone, Serialize)]
pub struct FeatureRow {
    pub feature: String,
    pub spec: SpecName,
    pub code: Vec<String>,
    pub last_shipped: Option<String>,
    pub staleness: Staleness,
}

/// The `KANSPEC-FEATURES.md` table, and the same rows `features --json` prints.
pub fn feature_rows(s: &Snapshot) -> Vec<FeatureRow> {
    s.specs
        .values()
        .map(|spec| FeatureRow {
            feature: spec.fm.feature.clone(),
            spec: spec.name.clone(),
            code: spec.fm.code.clone(),
            // "the last proposal that shipped a change to this spec" — read off the
            // `{p-xxxx}` provenance tokens the implementing branch wrote into the rule
            // bullets. There is no second ledger to disagree with them.
            last_shipped: spec
                .rules
                .iter()
                .rev()
                .find_map(|r| r.provenance.last())
                .map(|p| p.to_string()),
            staleness: derive::staleness(s, spec),
        })
        .collect()
}

/// The footer that replaces the `Fresh?` column, so a teammate reading the committed page
/// is told where freshness actually lives instead of quietly not being told at all.
///
/// It names `kanspec` literally rather than `cli::invoked_as()`: the binary a *particular*
/// process was invoked as is exactly the kind of ambient state a committed file may not
/// depend on — `ks` and `kanspec` must write the same bytes. `GENERATED_HEADER` hardcodes
/// the name for the same reason.
const FRESHNESS_FOOTER: &str =
    "\nStaleness is computed from git at read time, not stored here: `kanspec features --stale`.\n";

pub fn render_features(rows: &[FeatureRow]) -> String {
    let mut o = String::new();
    o.push_str(GENERATED_HEADER);
    o.push_str("\n# Feature map\n\n");
    if rows.is_empty() {
        o.push_str("No specs yet — `kanspec spec new <name> --code \"src/**\"`.\n");
        return o;
    }
    // Four columns, every one of them read out of the spec FILES. `FeatureRow::staleness`
    // is deliberately not among them — see the module header.
    o.push_str("| Feature | Spec | Code | Last shipped change |\n");
    o.push_str("|---|---|---|---|\n");
    for r in rows {
        o.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            cell(&r.feature),
            r.spec,
            if r.code.is_empty() {
                "—".to_string()
            } else {
                cell(&r.code.join(", "))
            },
            r.last_shipped.as_deref().unwrap_or("—"),
        ));
    }
    o.push_str(FRESHNESS_FOOTER);
    o
}

/// The one wording for a staleness verdict, shared by `features`, the `spec show` footer
/// and the board's feature strip — every one of them a LIVE read, so the terminal and the
/// board cannot disagree. The committed projection is not among them: see the module
/// header for why a disposable cache may not reach a git-tracked file.
pub fn fresh_cell(s: &Staleness) -> String {
    match s {
        Staleness::Ok => "ok".to_string(),
        Staleness::Stale { merges, .. } => format!("STALE: {merges} merges since"),
        Staleness::DeadGlobs { globs } => format!("dead globs: {}", globs.join(", ")),
        Staleness::NeverScanned => "never scanned".to_string(),
    }
}

pub fn render_architecture(s: &Snapshot) -> String {
    let mut o = String::new();
    o.push_str(GENERATED_HEADER);
    o.push_str("\n# Architecture decisions\n\n");

    let accepted: Vec<_> = s
        .decisions
        .values()
        .filter(|d| d.fm.status == DecisionStatus::Accepted)
        .collect();
    o.push_str(&format!("## Accepted decisions ({})\n", accepted.len()));
    if accepted.is_empty() {
        o.push_str("\nNone yet — `kanspec decide \"...\"` proposes one; a human accepts it.\n");
    }
    for d in &accepted {
        o.push_str(&format!("\n### {} — {}\n", d.fm.id, d.fm.title));
        o.push_str(&format!("\n- accepted {}\n", d.fm.date));
        if let Some(src) = &d.fm.source {
            o.push_str(&format!("- source: {src}\n"));
        }
        if !d.scope.is_empty() {
            o.push_str(&format!(
                "- scope: {}\n",
                d.scope
                    .iter()
                    .map(|g| format!("`{g}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if let Some(sup) = &d.fm.supersedes {
            o.push_str(&format!("- supersedes: {sup}\n"));
        }
        let body = d.body.trim_matches(['\n', '\r']).trim_end();
        if !body.is_empty() {
            o.push('\n');
            o.push_str(&demote(body));
            o.push('\n');
        }
    }

    // Landmine-grade quirks ride along: a teammate reading the architecture page needs to
    // know what will bite them, and it is the same registry `prime` injects path-scoped.
    let mines: Vec<_> = s
        .quirks
        .values()
        .filter(|q| q.fm.status == QuirkStatus::Active && q.fm.severity == Severity::Landmine)
        .collect();
    o.push_str(&format!("\n## Landmines ({})\n\n", mines.len()));
    if mines.is_empty() {
        o.push_str("None recorded.\n");
    }
    for q in &mines {
        o.push_str(&format!(
            "- **{}** {} — {}{}\n",
            q.fm.id,
            q.fm.title,
            if q.fm.paths.is_empty() {
                "everywhere".to_string()
            } else {
                q.fm.paths
                    .iter()
                    .map(|g| format!("`{g}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            },
            q.fm.source
                .as_ref()
                .map(|t| format!(" (learned in {t})"))
                .unwrap_or_default(),
        ));
    }
    o
}

/// Both projections as ops, so regeneration rides the ordinary write path.
///
/// D-20: every caller that changes a spec, a decision or a quirk pushes these into its OWN
/// plan, so the projections are rewritten inside the same lock that changed their source.
/// No caller may regenerate in a second transaction — that is the window in which the two
/// disagree.
pub fn plan_regenerate(s: &Snapshot, layout: &Layout) -> Result<Vec<Op>> {
    Ok(vec![
        Op::WriteGenerated {
            path: layout.features_md().to_path_buf(),
            contents: render_features(&feature_rows(s)),
        },
        Op::WriteGenerated {
            path: layout.architecture_md().to_path_buf(),
            contents: render_architecture(s),
        },
    ])
}

/// Rewrite both projections from whatever is on disk **now**. `Ok(false)` means they
/// already said the right thing and no byte moved.
///
/// **Every verb that mutates a spec, a decision or a quirk calls this**, not just `scan`.
/// DESIGN.md's sanctioned workflow edits specs directly on the implementation branch and
/// reviews them as an ordinary diff; if the committed feature map only caught up on the
/// next `scan`, the reviewer of that very PR would read the old prose — the exact silent
/// rot the projections exist to prevent. The verb that touched the source is the one that
/// republishes it, so the two land in the same `git status`. Rendering the map with
/// `features` is a READ and refreshes nothing; it must never be the only way to get a
/// current file.
///
/// D-20 asks for regeneration "inside the same lock" as the write that changed a spec or a
/// decision. This deliberately runs as its own short transaction immediately after that
/// write, for a reason the D-20 wording did not anticipate: a planner receives the
/// snapshot as it was **before** its own plan applies. Regenerating from that snapshot
/// would leave `KANSPEC-FEATURES.md` permanently one write behind — a brand-new spec would
/// be missing from the table until some *later* verb happened to run. `Store::transact`
/// reloads a fresh snapshot inside the lock, so a second transaction sees the write that
/// just landed.
///
/// The cost is R-1's window, one lock cycle wide: a crash between the two leaves the
/// projections one write stale, and the next verb or `scan` heals it. Being briefly stale
/// after a crash is recoverable; being permanently stale by construction is not.
/// Nothing is written when nothing changed. `scan` runs from the `post-merge` and
/// `post-checkout` hooks, i.e. on every checkout: rewriting two identical files each time
/// would take the advisory lock, bump `Snapshot::rev` and push an SSE frame at every open
/// browser tab, for no change anyone can see.
pub fn regenerate(ctx: &crate::ctx::Ctx) -> Result<bool> {
    let want = plan_regenerate(&ctx.snapshot()?, &ctx.layout)?;
    if want.iter().all(unchanged) {
        return Ok(false);
    }
    crate::store::Store::open(ctx).transact(
        // A projection rewrite transitions no ticket, which `transact` now says in the type
        // (round C granted S3/S5/S6's shared request). Under `sync = "commit"` this commits
        // as `kanspec: update <id>` rather than borrowing `Verb::Confirm`, whose meaning is
        // the human merge override (D-11).
        None,
        &ctx.invocation(),
        // Re-planned against the FRESH in-lock snapshot, never against the one read above:
        // that read happened without exclusivity, and trusting it is the TOCTOU
        // `Store::transact` reloads to avoid.
        |s, _m| Ok(crate::plan::Plan::of(plan_regenerate(s, &ctx.layout)?)),
    )?;
    Ok(true)
}

fn unchanged(op: &Op) -> bool {
    match op {
        Op::WriteGenerated { path, contents } => {
            std::fs::read_to_string(path).is_ok_and(|on_disk| &on_disk == contents)
        }
        _ => false,
    }
}

/// `init` refuses to claim a path that already exists un-generated.
pub fn is_ours(text: &str) -> bool {
    text.trim_start().starts_with(GENERATED_HEADER)
}

/// A markdown table cell: a literal `|` would end the column, and a newline would end the
/// row. Both are reachable from a `feature:` one-liner a human typed.
fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace(['\n', '\r'], " ")
}

/// A decision body is MADR-minimal — `## Context` / `## Decision` / `## Consequences` — and
/// it is embedded here under an `###` record heading. Left alone, its `##` headings would
/// un-nest the record they belong to and the page's own `## Landmines` section would read
/// as part of the last decision. Two levels down keeps the outline true.
fn demote(body: &str) -> String {
    body.lines()
        .map(|l| {
            if l.starts_with("##") {
                format!("##{l}")
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use crate::ids::{DecisionId, ProposalId, QuirkId, TicketId};
    use crate::model::{Decision, DecisionFm, Quirk, QuirkFm, Rule, Spec, SpecFm};
    use chrono::{NaiveDate, TimeZone, Utc};
    use std::collections::BTreeMap;

    fn snap() -> Snapshot {
        Snapshot::empty(
            Config::default(),
            Utc.with_ymd_and_hms(2026, 8, 31, 12, 0, 0).unwrap(),
        )
    }

    fn spec(name: &str) -> Spec {
        Spec {
            name: SpecName::parse(name).unwrap(),
            fm: SpecFm {
                feature: "Login | lockout".into(),
                code: vec!["src/auth/**".into()],
                stale_ack: None,
                extra: BTreeMap::new(),
            },
            path: "x".into(),
            body: String::new(),
            rules: vec![Rule {
                anchor: "auth.lockout".into(),
                text: "5 failed logins lock the account.".into(),
                provenance: vec![ProposalId::parse("p-7de2").unwrap()],
                line: 1,
            }],
        }
    }

    #[test]
    fn a_hand_written_file_is_not_ours_to_overwrite() {
        assert!(is_ours(&format!("{GENERATED_HEADER}\n# Feature map\n")));
        assert!(!is_ours("# Our own FEATURES.md\n"));
    }

    #[test]
    fn both_projections_wear_the_header_that_stops_hand_edits() {
        let mut s = snap();
        let sp = spec("auth");
        s.specs.insert(sp.name.clone(), sp);
        assert!(is_ours(&render_features(&feature_rows(&s))));
        assert!(is_ours(&render_architecture(&s)));
    }

    #[test]
    fn a_pipe_in_a_feature_one_liner_cannot_break_the_table() {
        let mut s = snap();
        let sp = spec("auth");
        s.specs.insert(sp.name.clone(), sp);
        let md = render_features(&feature_rows(&s));
        let row = md
            .lines()
            .find(|l| l.contains("auth"))
            .expect("the auth row");
        // Four columns, so five delimiters — and the escaped pipe from the one-liner is
        // not one of them.
        assert_eq!(row.matches('|').count() - row.matches("\\|").count(), 5);
    }

    #[test]
    fn regeneration_is_byte_stable_so_a_scan_does_not_dirty_the_tree() {
        let mut s = snap();
        let sp = spec("auth");
        s.specs.insert(sp.name.clone(), sp);
        // No clock, no env, no ordering surprise: the same corpus renders the same bytes,
        // which is what keeps the committed projections out of every checkout's diff.
        assert_eq!(
            render_features(&feature_rows(&s)),
            render_features(&feature_rows(&s))
        );
        assert_eq!(render_architecture(&s), render_architecture(&s));
    }

    /// The committed projection may not depend on `cache/gitstate.json`.
    ///
    /// Holding the cache fixed and rendering twice only proves the renderer is a function;
    /// it says nothing about the input the cache contributes. This VARIES the cache across
    /// the whole range one can be in — absent (a fresh clone), scanned-and-clean, and
    /// scanned-with-rotted-globs — and demands identical bytes, because two clones of one
    /// commit differ in exactly this and in nothing else.
    #[test]
    fn the_committed_feature_map_ignores_the_disposable_cache_entirely() {
        let mut s = snap();
        let sp = spec("auth");
        let name = sp.name.clone();
        s.specs.insert(name.clone(), sp);

        // A fresh clone: nobody has run `scan` here.
        assert!(s.git.specs.is_empty());
        let cold = render_features(&feature_rows(&s));
        assert!(matches!(
            derive::staleness(&s, &s.specs[&name]),
            Staleness::NeverScanned
        ));

        // Scanned, globs alive.
        s.git.specs.insert(
            name.clone(),
            crate::cache::SpecAnchor {
                last_edit_sha: Some("a1b9c3d5f00".into()),
                last_edit_at: Some(Utc.with_ymd_and_hms(2026, 8, 20, 9, 0, 0).unwrap()),
                merges_since: 0,
                dead_globs: Vec::new(),
            },
        );
        let scanned = render_features(&feature_rows(&s));

        // Scanned, and every glob has rotted — the loudest verdict there is.
        s.git.specs.get_mut(&name).unwrap().dead_globs = vec!["src/auth/**".into()];
        let rotted = render_features(&feature_rows(&s));
        assert!(matches!(
            derive::staleness(&s, &s.specs[&name]),
            Staleness::DeadGlobs { .. }
        ));

        assert_eq!(
            cold, scanned,
            "a clone that has never scanned must commit the same bytes as one that has"
        );
        assert_eq!(
            scanned, rotted,
            "glob rot is a live finding, not a fact to commit"
        );
        for verdict in ["never scanned", "dead globs", "STALE:"] {
            assert!(
                !cold.contains(verdict),
                "`{verdict}` is cache state and must not reach a git-tracked file:\n{cold}"
            );
        }
        // …and the page still tells the reader where freshness DOES live.
        assert!(cold.contains("features --stale"), "{cold}");
    }

    #[test]
    fn only_accepted_decisions_and_active_landmines_reach_the_architecture_page() {
        let mut s = snap();
        for (id, status) in [
            ("D-8c1a", DecisionStatus::Accepted),
            ("D-2c77", DecisionStatus::Proposed),
            ("D-3d88", DecisionStatus::Revoked),
        ] {
            let d = Decision {
                fm: DecisionFm {
                    id: DecisionId::parse(id).unwrap(),
                    title: format!("decision {id}"),
                    status,
                    date: NaiveDate::from_ymd_opt(2026, 9, 2).unwrap(),
                    source: Some("p-7de2#p1".into()),
                    scope: vec!["src/auth/**".into()],
                    supersedes: None,
                    superseded_by: None,
                    extra: BTreeMap::new(),
                },
                path: "x".into(),
                body: "## Decision\nRedis.\n".into(),
                scope: vec!["src/auth/**".into()],
            };
            s.decisions.insert(d.fm.id.clone(), d);
        }
        for (id, sev, st) in [
            ("q-11ba", Severity::Landmine, QuirkStatus::Active),
            ("q-22cd", Severity::Gotcha, QuirkStatus::Active),
            ("q-33ef", Severity::Landmine, QuirkStatus::Fixed),
        ] {
            let q = Quirk {
                fm: QuirkFm {
                    id: QuirkId::parse(id).unwrap(),
                    title: format!("quirk {id}"),
                    paths: vec!["src/billing/**".into()],
                    severity: sev,
                    status: st,
                    source: Some(TicketId::parse("t-8812").unwrap()),
                    fixed_by: None,
                    extra: BTreeMap::new(),
                },
                path: "x".into(),
                body: String::new(),
            };
            s.quirks.insert(q.fm.id.clone(), q);
        }
        let md = render_architecture(&s);
        assert!(md.contains("D-8c1a"));
        assert!(!md.contains("D-2c77"), "proposed is not architecture");
        assert!(!md.contains("D-3d88"), "revoked is not architecture");
        assert!(md.contains("q-11ba"));
        assert!(!md.contains("q-22cd"), "only landmine-grade rides along");
        assert!(!md.contains("q-33ef"), "a fixed quirk is retired");
    }
}
