//! The generated projections: `KANSPEC-FEATURES.md` and `KANSPEC-ARCHITECTURE.md`, both
//! written to the **repo root** where a teammate browsing GitHub will find them.
//!
//! Projections cannot rot independently of their sources — which is exactly why they are
//! safe to put in plain sight. Regenerated on `scan`, and on any `transact` that touched a
//! spec or a decision (D-20), through `Op::WriteGenerated` inside the same lock.
//!
//! Owner: **S6**.

// Wave-0 skeleton. The bodies below are `todo!("S6: …")`; these two allows exist ONLY so
// the skeleton compiles clippy-clean and MUST be deleted by S6 when the bodies land.
#![allow(unused_variables, dead_code)]

use serde::Serialize;

use crate::derive::Staleness;
use crate::error::Result;
use crate::ids::SpecName;
use crate::model::Snapshot;
use crate::paths::Layout;
use crate::plan::Op;

/// The header that stops hand-edits. Present on both projections, byte-identical.
pub const GENERATED_HEADER: &str =
    "<!-- GENERATED by kanspec. Edit the sources (.kanspec/specs, .kanspec/decisions), not this file. -->";

#[derive(Debug, Clone, Serialize)]
pub struct FeatureRow {
    pub feature: String,
    pub spec: SpecName,
    pub code: Vec<String>,
    pub last_shipped: Option<String>,
    pub staleness: Staleness,
}

/// The `KANSPEC-FEATURES.md` table, and the same rows `features --json` prints.
pub fn feature_rows(s: &Snapshot) -> Vec<FeatureRow> {
    todo!("S6: one row per spec — frontmatter feature + code globs + the last proposal that shipped a change + derive::staleness")
}

pub fn render_features(rows: &[FeatureRow]) -> String {
    todo!("S6: GENERATED_HEADER + the DESIGN.md feature-map table")
}

pub fn render_architecture(s: &Snapshot) -> String {
    todo!("S6: GENERATED_HEADER + accepted decisions with scope and provenance, plus active landmine quirks")
}

/// Both projections as ops, so regeneration rides the ordinary write path.
pub fn plan_regenerate(s: &Snapshot, layout: &Layout) -> Result<Vec<Op>> {
    todo!("S6: two Op::WriteGenerated, one per projection path from [paths]")
}

/// `init` refuses to claim a path that already exists un-generated.
pub fn is_ours(text: &str) -> bool {
    text.trim_start().starts_with(GENERATED_HEADER)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_hand_written_file_is_not_ours_to_overwrite() {
        assert!(is_ours(&format!("{GENERATED_HEADER}\n# Feature map\n")));
        assert!(!is_ours("# Our own FEATURES.md\n"));
    }
}
